#
###################################
# Site wide configuration
####################################
#
title:       "neomorning's blog"
description: > # this means to ignore newlines until "baseurl:"
  Code monkey, soldering fume maker, fantasy/scifi addict, whah?
  A blog for like-minded people, and a notepad
  for myself. Have fun...
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Canada/Toronto
markdown:          kramdown
highlighter:       Rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: neomorning
  avatar: avatar.jpg
  job: "Developer"
  bio: "Code monkey, fantasy/scifi/coffee addict, soldering fume maker, whah? A blog for like-minded people, and a notepad for myself. Have fun..."
  # email: zourenyuan@gmail.com
  disqus-shortname:
  twitter: annienmao #username
  facebook: #username
  # google:
  #   plus: #username
  #   analytics: UA-62251910-1
  #   verify:
  #   ad-client:
  #   ad-slot:
  bing-verify:
  github: maoning #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
