# Site settings
title: neomorning
description: > # this means to ignore newlines until "baseurl:"
  Code monkey, soldering fume maker,  whah? A blog for the like-minded people, and a note pad
  for myself. Have fun...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: annienmao
github_username:  maoning
highlighter:      pygments

# Build settings
markdown: kramdown

# Permalink Style
permalink: /blog/:month-:day-:year/:title.html

# Number of Posts Displayed per Page
paginate: 10
paginate_path: "/blog/page:num/"

# default values
defaults:
   -
      scope:
         path: "" # all posts
      values:
         layout: "default"
