# Site settings
title: neomorning
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: annienmao
github_username:  maoning
highlighter:      pygments

# Build settings
markdown: kramdown

# Permalink Style
permalink: /blog/:month-:day-:year/:title.html

# Number of Posts Displayed per Page
paginate: 10
paginate_path: "/blog/page:num/"

# default values
defaults:
   -
      scope:
         path: "" # all posts
      values:
         layout: "default"
